### ISSUE TITLE
Names do not match

### ISSUE THREAD

**Issue by aimansnigdha** [andrealoddo/MP-IDB-The-Malaria-Parasite-Image-Database-for-Image-Processing-and-Analysis#1]
For three images in the Falciparum folder, their ground truth does not match (mixup with -/_).

Falciparum/ 
img/ 1701151546-0012-R, 1701151546-0013-R_T, 1701151546-0014-R 
gt/ 1701151546-0012_R, 1701151546-0013_R-T, 1701151546-0014_R

**Comment by andrealoddo** [comment]
Thank you for your notice. I corrected the mismatch in the filenames.
